import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cabecalhoPrincipal: {
    height: 160,
    width: "100%",
    padding: 16,
    backgroundColor: "#053D6E",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "column",
    position: "relative",
    fontFamily: "Roboto",
  },
  botaoVoltar: {
    position: "absolute",
    left: 16,
    top: 10,
    borderWidth: 1,
    borderColor: "#0188EA",
    borderRadius: 20,
    padding: 15,
  },
  flecha: {
    width: 30,
    height: 25,
  },
  cabecalhoTitulo: {
    fontSize: 20,
    color: "#ffffff",
    fontFamily: "Roboto, sans",
    fontWeight: "bold",
  },
  container: {
    flex: 1,
    backgroundColor: "#053D6E",
    fontFamily: "Roboto, sans",
  },
  botaoAlternado: {
    height: 39,
    width: 255,
    backgroundColor: "#FFFFFF80",
    borderRadius: 25,
    flexDirection: "row",
    justifyContent: "center",
    color: "#053D6E",
    fontSize: 16,
    marginBottom: 20,
  },
  cards: {
    paddingTop: 33,
    width: "100%",
    backgroundColor: "#D9D9D9",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    height: "100%",
    paddingLeft: 10,
    paddingRight: 10,
  },
  card: {
    height: 76,
    borderRadius: 8,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardConteudo: {
    width: "70%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 10,
  },
  iconeCategoria: {
    width: 55,
    height: 55,
    marginRight: 13,
  },
  pontinhos: {
    height: 28,
    width: 6,
    marginRight: 7,
  },
  menu: {
    position: "absolute",
    top: 60,
    right: 0,
    backgroundColor: "white",
    borderRadius: 5,
    padding: 10,
    zIndex: 1,
    width: 150,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  opcao: {
    paddingVertical: 5,
    color: "#727272",
    fontSize: 20,
    lineHeight: 23.44

  },
});